// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6Cdo0_obmVeaLVUB7qR9jj1widULFIg',
    appId: '1:240186795325:web:bcd2239b9da9b91a109154',
    messagingSenderId: '240186795325',
    projectId: 'chatapplication-de7b4',
    authDomain: 'chatapplication-de7b4.firebaseapp.com',
    storageBucket: 'chatapplication-de7b4.firebasestorage.app',
    measurementId: 'G-NR9SLRBQTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACRhu8--N429x4Fthrtncr69czTFvD51w',
    appId: '1:240186795325:android:99cb479339c77d86109154',
    messagingSenderId: '240186795325',
    projectId: 'chatapplication-de7b4',
    storageBucket: 'chatapplication-de7b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxLF765G_oAnZlm4kkedKRL5JE2YGbNqs',
    appId: '1:240186795325:ios:86821a9b2892d60a109154',
    messagingSenderId: '240186795325',
    projectId: 'chatapplication-de7b4',
    storageBucket: 'chatapplication-de7b4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxLF765G_oAnZlm4kkedKRL5JE2YGbNqs',
    appId: '1:240186795325:ios:86821a9b2892d60a109154',
    messagingSenderId: '240186795325',
    projectId: 'chatapplication-de7b4',
    storageBucket: 'chatapplication-de7b4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ6Cdo0_obmVeaLVUB7qR9jj1widULFIg',
    appId: '1:240186795325:web:edaa0a17725fbba2109154',
    messagingSenderId: '240186795325',
    projectId: 'chatapplication-de7b4',
    authDomain: 'chatapplication-de7b4.firebaseapp.com',
    storageBucket: 'chatapplication-de7b4.firebasestorage.app',
    measurementId: 'G-H92DGM0203',
  );

}